spring:
  datasource:
#      БД не сохраняется (данные есть, пока запущен сервис)
    url: jdbc:h2:mem:testdb
#    создается файл с БД
#    url: jdbc:h2:file:./db
    username: sa
    password:
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  h2:
    console:
        enabled: true
        path: /h2-console